package com.bwie.zhangzili20190120.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwie.zhangzili20190120.greendao.ShopBeanDao;

import com.bwie.zhangzili20190120.db.ShopBeanDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopBeanDaoDaoConfig;

    private final ShopBeanDaoDao shopBeanDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopBeanDaoDaoConfig = daoConfigMap.get(ShopBeanDaoDao.class).clone();
        shopBeanDaoDaoConfig.initIdentityScope(type);

        shopBeanDaoDao = new ShopBeanDaoDao(shopBeanDaoDaoConfig, this);

        registerDao(ShopBeanDao.class, shopBeanDaoDao);
    }
    
    public void clear() {
        shopBeanDaoDaoConfig.clearIdentityScope();
    }

    public ShopBeanDaoDao getShopBeanDaoDao() {
        return shopBeanDaoDao;
    }

}
